### ISSUE TITLE
Error: WARNING: Date in past. Will never be fired.

### ISSUE THREAD

**Issue by m-schaeffler** [csuermann/node-red-contrib-presence-faker#56]
Node-Red crashed with this log entries:

```
18 Nov 22:36:03 - [red] Uncaught Exception:
18 Nov 22:36:03 - [error] Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/srv/node-red/.node-red/node_modules/cron/dist/time.js:93:23)
    at CronTime.getTimeout (/srv/node-red/.node-red/node_modules/cron/dist/time.js:110:34)
    at Timeout.callbackWrapper [as _onTimeout] (/srv/node-red/.node-red/node_modules/cron/dist/job.js:119:48)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Consumed 50min 29.062s CPU time.
nodered.service: Scheduled restart job, restart counter is at 2.
Stopped nodered.service - Node-RED graphical event wiring tool.
nodered.service: Consumed 50min 29.062s CPU time.
Starting nodered.service - Node-RED graphical event wiring tool...
Started nodered.service - Node-RED graphical event wiring tool.
18 Nov 22:36:26 - [info]
Willkommen bei Node-RED

18 Nov 22:36:26 - [info] Node-RED Version: v3.1.0
18 Nov 22:36:26 - [info] Node.js  Version: v20.5.1
18 Nov 22:36:26 - [info] Linux 6.1.0-rpi6-rpi-v7l arm LE
18 Nov 22:36:29 - [info] Paletten-Nodes werden geladen
18 Nov 22:36:33 - [info] Dashboard version 3.6.1 started at /ui
```

Environment:
-     Node-RED version: 3.1.0
-     Node.js version: 20.5.1
-     npm version:
-     Platform/OS: Raspberry OS bookworm
-     Browser: no connection at this time

**Comment by m-schaeffler** [comment]
This is caused by presence faker, as it is the only node that includes cron.

**Comment by csuermann** [comment]
Hi @m-schaeffler,

Thanks for reporting this issue. Which version of presence-faker are you using?

**Comment by TKSS3** [comment]
I'm having the same issue, I'm using version 1.8.8 of presence-faker

**Comment by nlanfran** [comment]
Same issue with me:


`
Node-RED[429]: 25 Jul 23:33:05 - [red] Uncaught Exception:

Node-RED[429]: 25 Jul 23:33:05 - [error] Error: WARNING: Date in past. Will never be fired.

Node-RED[429]:     at CronTime.sendAt (/home/pi/.node-red/node_modules/node-red-contrib-presence-faker/node_modules/cron/dist/time.js:93:23)

Node-RED[429]:     at CronTime.getTimeout (/home/pi/.node-red/node_modules/node-red-contrib-presence-faker/node_modules/cron/dist/time.js:110:34)

Node-RED[429]:     at Timeout.callbackWrapper [as _onTimeout] (/home/pi/.node-red/node_modules/node-red-contrib-presence-faker/node_modules/cron/dist/job.js:119:48)

Node-RED[429]:     at listOnTimeout (internal/timers.js:557:17)
Node-RED[429]:     at processTimers (internal/timers.js:500:7)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Consumed 21min 2.405s CPU time.
nodered.service: Scheduled restart job, restart counter is at 1.
Stopped Node-RED graphical event wiring tool.
nodered.service: Consumed 21min 2.405s CPU time.
Started Node-RED graphical event wiring tool.
Node-RED[3333]: 25 Jul 23:33:26 - [info]
Node-RED[3333]: Welcome to Node-RED
Node-RED[3333]: ===================
Node-RED[3333]: 25 Jul 23:33:26 - [info] Node-RED version: v2.2.2
Node-RED[3333]: 25 Jul 23:33:26 - [info] Node.js  version: v14.21.3
Node-RED[3333]: 25 Jul 23:33:26 - [info] Linux 6.1.21-v8+ arm LE
Node-RED[3333]: 25 Jul 23:33:27 - [info] Loading palette nodes
`

**Comment by A380Coding** [comment]
I'm having the same issue. I can see this issue beeing open for some time. Is there any update? Any additional data I could check to identify where it is coming from?
Using Versoin 1.8.11

![Image](https://github.com/user-attachments/assets/b7f7157f-2288-436a-a56d-277d5e9600de)

**Comment by ssillen** [comment]
I'm also having the same issue. Currently on v1.8.8
It causes Node Red to restart, which interrupts some of my flows.

Settings:

![Image](https://github.com/user-attachments/assets/4daebe9c-7df7-4d0a-a7bb-443745f995cc)

In the log, the error occurs at 21:18:49, however in the prepared schedule I don't see anything strange for the part at 21:18:49
Might be something with time conversion?
Log:
```
4 May 19:30:00 - [warn] [presence-faker:Presence faker hal] created new schedule: [{"isOn":true,"duration":104,"beginString":"19:30:00","endString":"19:31:44","begin":"2025-05-04T17:30:00.000Z"},{"isOn":false,"duration":1165,"beginString":"19:31:44","endString":"19:51:09","begin":"2025-05-04T17:31:44.000Z"},{"isOn":true,"duration":138,"beginString":"19:51:09","endString":"19:53:27","begin":"2025-05-04T17:51:09.000Z"},{"isOn":false,"duration":1351,"beginString":"19:53:27","endString":"20:15:58","begin":"2025-05-04T17:53:27.000Z"},{"isOn":true,"duration":170,"beginString":"20:15:58","endString":"20:18:48","begin":"2025-05-04T18:15:58.000Z"},{"isOn":false,"duration":1351,"beginString":"20:18:48","endString":"20:41:19","begin":"2025-05-04T18:18:48.000Z"},{"isOn":true,"duration":153,"beginString":"20:41:19","endString":"20:43:52","begin":"2025-05-04T18:41:19.000Z"},{"isOn":false,"duration":772,"beginString":"20:43:52","endString":"20:56:44","begin":"2025-05-04T18:43:52.000Z"},{"isOn":true,"duration":152,"beginString":"20:56:44","endString":"20:59:16","begin":"2025-05-04T18:56:44.000Z"},{"isOn":false,"duration":193,"beginString":"20:59:16","endString":"21:02:29","begin":"2025-05-04T18:59:16.000Z"},{"isOn":true,"duration":208,"beginString":"21:02:29","endString":"21:05:57","begin":"2025-05-04T19:02:29.000Z"},{"isOn":false,"duration":772,"beginString":"21:05:57","endString":"21:18:49","begin":"2025-05-04T19:05:57.000Z"},{"isOn":true,"duration":143,"beginString":"21:18:49","endString":"21:21:12","begin":"2025-05-04T19:18:49.000Z"},{"isOn":false,"duration":772,"beginString":"21:21:12","endString":"21:34:04","begin":"2025-05-04T19:21:12.000Z"},{"isOn":true,"duration":178,"beginString":"21:34:04","endString":"21:37:02","begin":"2025-05-04T19:34:04.000Z"},{"isOn":false,"duration":965,"beginString":"21:37:02","endString":"21:53:07","begin":"2025-05-04T19:37:02.000Z"},{"isOn":true,"duration":184,"beginString":"21:53:07","endString":"21:56:11","begin":"2025-05-04T19:53:07.000Z"},{"isOn":false,"duration":965,"beginString":"21:56:11","endString":"22:12:16","begin":"2025-05-04T19:56:11.000Z"},{"isOn":true,"duration":67,"beginString":"22:12:16","endString":"22:13:23","begin":"2025-05-04T20:12:16.000Z"},{"isOn":false,"duration":386,"beginString":"22:13:23","endString":"22:19:49","begin":"2025-05-04T20:13:23.000Z"},{"isOn":true,"duration":134,"beginString":"22:19:49","endString":"22:22:03","begin":"2025-05-04T20:19:49.000Z"},{"isOn":false,"duration":772,"beginString":"22:22:03","endString":"22:34:55","begin":"2025-05-04T20:22:03.000Z"},{"isOn":true,"duration":174,"beginString":"22:34:55","endString":"22:37:49","begin":"2025-05-04T20:34:55.000Z"},{"isOn":false,"duration":1931,"beginString":"22:37:49","endString":"23:10:00","begin":"2025-05-04T20:37:49.000Z"}]
4 May 19:30:00 - [warn] [presence-faker:Presence faker hal] executing block: {"isOn":true,"duration":104,"beginString":"19:30:00","endString":"19:31:44","begin":"2025-05-04T17:30:00.000Z"}
4 May 19:30:00 - [warn] [presence-faker:Presence faker hal] new node status: ON [19:30:00 - 19:31:44]
4 May 19:30:00 - [warn] [presence-faker:Presence faker hal] installed crons for 23 blocks
4 May 19:31:44 - [warn] [presence-faker:Presence faker hal] executing block: {"isOn":false,"duration":1165,"beginString":"19:31:44","endString":"19:51:09","begin":"2025-05-04T17:31:44.000Z"}
4 May 19:31:44 - [warn] [presence-faker:Presence faker hal] new node status: OFF [19:31:44 - 19:51:09]
4 May 19:51:09 - [warn] [presence-faker:Presence faker hal] executing block: {"isOn":true,"duration":138,"beginString":"19:51:09","endString":"19:53:27","begin":"2025-05-04T17:51:09.000Z"}
4 May 19:51:09 - [warn] [presence-faker:Presence faker hal] new node status: ON [19:51:09 - 19:53:27]
4 May 19:53:27 - [warn] [presence-faker:Presence faker hal] executing block: {"isOn":false,"duration":1351,"beginString":"19:53:27","endString":"20:15:58","begin":"2025-05-04T17:53:27.000Z"}
4 May 19:53:27 - [warn] [presence-faker:Presence faker hal] new node status: OFF [19:53:27 - 20:15:58]
4 May 20:15:58 - [warn] [presence-faker:Presence faker hal] executing block: {"isOn":true,"duration":170,"beginString":"20:15:58","endString":"20:18:48","begin":"2025-05-04T18:15:58.000Z"}
4 May 20:15:58 - [warn] [presence-faker:Presence faker hal] new node status: ON [20:15:58 - 20:18:48]
4 May 20:18:48 - [warn] [presence-faker:Presence faker hal] executing block: {"isOn":false,"duration":1351,"beginString":"20:18:48","endString":"20:41:19","begin":"2025-05-04T18:18:48.000Z"}
4 May 20:18:48 - [warn] [presence-faker:Presence faker hal] new node status: OFF [20:18:48 - 20:41:19]
4 May 20:41:19 - [warn] [presence-faker:Presence faker hal] executing block: {"isOn":true,"duration":153,"beginString":"20:41:19","endString":"20:43:52","begin":"2025-05-04T18:41:19.000Z"}
4 May 20:41:19 - [warn] [presence-faker:Presence faker hal] new node status: ON [20:41:19 - 20:43:52]
4 May 20:43:52 - [warn] [presence-faker:Presence faker hal] executing block: {"isOn":false,"duration":772,"beginString":"20:43:52","endString":"20:56:44","begin":"2025-05-04T18:43:52.000Z"}
4 May 20:43:52 - [warn] [presence-faker:Presence faker hal] new node status: OFF [20:43:52 - 20:56:44]
4 May 20:56:44 - [warn] [presence-faker:Presence faker hal] executing block: {"isOn":true,"duration":152,"beginString":"20:56:44","endString":"20:59:16","begin":"2025-05-04T18:56:44.000Z"}
4 May 20:56:44 - [warn] [presence-faker:Presence faker hal] new node status: ON [20:56:44 - 20:59:16]
4 May 20:59:16 - [warn] [presence-faker:Presence faker hal] executing block: {"isOn":false,"duration":193,"beginString":"20:59:16","endString":"21:02:29","begin":"2025-05-04T18:59:16.000Z"}
4 May 20:59:16 - [warn] [presence-faker:Presence faker hal] new node status: OFF [20:59:16 - 21:02:29]
4 May 21:02:29 - [warn] [presence-faker:Presence faker hal] executing block: {"isOn":true,"duration":208,"beginString":"21:02:29","endString":"21:05:57","begin":"2025-05-04T19:02:29.000Z"}
4 May 21:02:29 - [warn] [presence-faker:Presence faker hal] new node status: ON [21:02:29 - 21:05:57]
4 May 21:05:57 - [warn] [presence-faker:Presence faker hal] executing block: {"isOn":false,"duration":772,"beginString":"21:05:57","endString":"21:18:49","begin":"2025-05-04T19:05:57.000Z"}
4 May 21:05:57 - [warn] [presence-faker:Presence faker hal] new node status: OFF [21:05:57 - 21:18:49]
4 May 21:18:49 - [red] Uncaught Exception:
4 May 21:18:49 - [error] Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/config/node_modules/cron/dist/time.js:93:23)
    at CronTime.getTimeout (/config/node_modules/cron/dist/time.js:110:34)
    at Timeout.callbackWrapper [as _onTimeout] (/config/node_modules/cron/dist/job.js:119:48)
    at listOnTimeout (node:internal/timers:594:17)
    at processTimers (node:internal/timers:529:7)
[21:18:49] INFO: [32mService Node-RED exited with code 1 (by signal 0)[0m
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
```

**Comment by A380Coding** [comment]
Happening to me as well. Is there any update? Seems to mostly happen when the days get shorter (summer->winter)
